# Generated by Django 4.2.27 on 2026-02-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('step', models.CharField(default='start', max_length=50)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('game', models.CharField(max_length=255)),
                ('master', models.CharField(max_length=255)),
                ('place_number', models.IntegerField()),
                ('day', models.IntegerField()),
                ('line', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='bot.telegramuser')),
            ],
        ),
    ]
